dbt_snowflake_project:
  outputs:
    dev:
      account: ********* #snowflake account
      database: dbt_db
      password: ******** #snowflake account password
      role: dbt_role
      schema: dbt_schema
      threads: 10
      type: snowflake
      user: ARBAZMOHAMMAD
      warehouse: dbt_wh
  target: dev
